# fly.toml app configuration file generated for tigerbeetle on 2023-10-17T15:15:59+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "tigerbeetle"
primary_region = "ams"

[build]
  dockerfile = "/tools/docker/Dockerfile"
  ignorefile = "/tools/docker/.dockerignore"

[[mounts]]
  source = "data"
  destination = "/data"

[[services]]
  protocol = "tcp"
  internal_port = 3000
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
